version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      interval: 20s
      retries: 10
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=500ms",
        ]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    healthcheck:
      interval: 10s
      retries: 20
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:5601/api/status | grep -q 'All services are available'",
        ]

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.17.4
    container_name: apm-server
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "8200:8200"
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      - apm-server.kibana.enabled=true
      - apm-server.kibana.host=http://kibana:5601
      - apm-server.secret_token=changeme
      - apm-server.rum.enabled=true
      - xpack.security.enabled=false
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.host=0.0.0.0:8200
        -E setup.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

volumes:
  esdata:
